### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [DanMcInerney/cookiejack#2]
As you probably know by know I am a developer for the archassault project and we would like to distribute this tool. However I noticed its missing a license file, I checked the readme and the py file itself. If you arent ready for this to be distributed thats fine I will keep an eye and check back with you at a later date.

Thanks
Tyler

**Comment by DanMcInerney** [comment]
Yeah it's not ready. It's super inconsistent at the moment for reasons that
elude me.

**Comment by archey** [comment]
Ok no problem, I will keep an eye on it feel free to let me know when its ready. We will be including most of your python tools in our repository if we can.

**Comment by archey** [comment]
Is this ready yet? Or did it go by the wayside and die?

**Comment by DanMcInerney** [comment]
I never got it working, it's currently abandoned.

**Comment by archey** [comment]
On February 18, 2015 1:16:42 PM EST, Dan McInerney notifications@github.com wrote:

> I never got it working, it's currently abandoned.
> 
> On Wed, Feb 18, 2015 at 11:14 AM, arch3y notifications@github.com
> wrote:
> 
> > Is this ready yet? Or did it go by the wayside and die?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/DanMcInerney/cookiejack/issues/2#issuecomment-74916152
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DanMcInerney/cookiejack/issues/2#issuecomment-74916642

Ok no problem, just curious. I just noticed i have a bunch of open gh issues.
